# Generated by Django 5.0.7 on 2026-08-25 08:22

import django.db.models.deletion
import presentations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=presentations.models.make_token, max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=60)),
                ('expertise_tag', models.CharField(max_length=60)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_slug', models.SlugField(max_length=80)),
                ('join_code', models.CharField(default=presentations.models.make_join_code, max_length=6, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('current_slide_id', models.CharField(blank=True, default='', max_length=80)),
                ('interaction_states', models.JSONField(blank=True, default=dict)),
                ('video_state', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_slug', models.SlugField(max_length=80)),
                ('slide_id', models.CharField(db_index=True, max_length=80)),
                ('anchor', models.JSONField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=60)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presentations.participant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='presentations.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='presentations.session')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='presentations.session'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('participant', 'interaction_id'), name='uniq_response_per_participant'),
        ),
    ]
