# Generated by Django 5.0.7 on 2026-08-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('is_locked', False)), fields=('deck_slug',), name='uniq_open_session_per_deck'),
        ),
    ]
