# Generated by Django 5.0.7 on 2026-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        help_text="Poster image (JPG/PNG)", upload_to="posters/images/"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        help_text="Poster PDF file", upload_to="posters/pdfs/"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#453e5d",
                        help_text="Hex color code (e.g., #453e5d)",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color code (e.g., #ffffff)",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Display this poster on the website"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which to display (lower numbers first)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poster",
                "verbose_name_plural": "Posters",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
